name: upper_keyboard_view_with_photo_and_send_icon
description: "upper keyboard view with photo and send icon"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/upper_keyboard_view_with_photo_and_send_icon

version: 1.0.6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  universal_io: #@add

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more: #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/upper_keyboard_view_with_photo_and_send_icon/
  uses-material-design: true